### ISSUE TITLE
HotRod client not working

### ISSUE THREAD

**Issue by ryanemerson** [infinispan/infinispan-quarkus#3]
HotRod operations are not working as expected in the JVM and native binary.

1. `.getCache("user-cache")` for user defined cache always retuns null
2. Operations on internal caches fail with `Unauthorized '' opearation
3. `.getCacheNames()` throws `.HotRodClientException:Request for messageId=6 returned server error (status=0x85): java.lang.SecurityException: ISPN006017: Unauthorized 'EXEC' operation`
4. Creating a cache fails with `Unauthorized 'EXEC' operation`

Tests to reproduce are on this branch: https://github.com/ryanemerson/infinispan-quarkus/tree/%233_hotrod_failures

**Comment by wburns** [comment]
This is handled by https://github.com/infinispan/infinispan-quarkus/pull/6
