### ISSUE TITLE
Can you please update the quarkus tutorial for Quarkus 1.10.2

### ISSUE THREAD

**Issue by hrstoyanov** [infinispan/infinispan-quarkus#43]
- the tutorial does not provide any help besides hinting at:
```
@Inject EmbeddedCacheManager cache;
```

- Adding infinispan extension to Gradle project does not work:
```
dependencies {
    //neither of these works!
   implementation 'org.infinispan:quarkus-infinispan-embedded'
   implementation 'io.quarkus:quarkus-infinispan-embedded'
}
```

```
Execution failed for task ':recres-webapp:quarkusGenerateCode'.
> Could not resolve all dependencies for configuration ':recres-webapp:runtimeClasspath'.
   > Could not find io.quarkus:quarkus-infinispan-embedded:.
     Required by:
         project :recres-webapp
```

**Comment by StephenOTT** [comment]
any direction on this?  We see that v15 of infinispan appears to have some movement in maven, but v14 does not have any releases.

Is embedded version intended to be used?

**Comment by ryanemerson** [comment]
@StephenOTT The 14.0.x modules should have been released as well, however our release automation has been failing silently. I've created a PR to fix this for 14.0.26.Final which should be released next week https://github.com/infinispan/infinispan-quarkus/pull/137

**Comment by StephenOTT** [comment]
Great. Thanks!

**Comment by ryanemerson** [comment]
Sorry for the delay. Now that 15.0.0.Final is out, we will no longer maintain the Quarkus extensions for 14.0.x. Please upgrade to Infinispan 15 and you should be able to consume the maven artifacts.
